name: bijak
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  flutter: 
    sdk: flutter
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/data/

